name: Build AutoVideoEditor

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # Ubuntu/Linux 依赖安装
    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libgl1-mesa-glx ffmpeg
        sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 /usr/lib/x86_64-linux-gnu/libxcb-util.so.0
    
    # Windows 依赖安装
    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install ffmpeg -y
    
    # macOS 依赖安装
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install ffmpeg
    
    # 分别处理 Python 依赖（避免 PowerShell 和 Bash 语法冲突）
    - name: Install Python dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install wheel pyinstaller opencv-python numpy moviepy imageio imageio-ffmpeg tqdm PyQt5 PyQt5-sip
    
    - name: Install Python dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install wheel pyinstaller opencv-python numpy moviepy imageio imageio-ffmpeg tqdm PyQt5
    
    - name: Install Python dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        python -m pip install --upgrade pip
        pip install wheel pyinstaller opencv-python numpy moviepy imageio imageio-ffmpeg tqdm PyQt5 PyQt5-Qt5
    
    - name: Prepare build
      run: |
        echo "Version 1.0.0" > version.txt
        echo "Build OS: ${{ runner.os }}" >> version.txt
        echo "Build time: $(date)" >> version.txt
      
    # Windows 构建
    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --name AutoVideoEditor --onefile --windowed --add-data="version.txt;." --icon=src/icons/icon.ico src/main.py
        7z a -tzip AutoVideoEditor_Windows.zip dist/AutoVideoEditor.exe
      
    # macOS 构建
    - name: Build application (macOS)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --name AutoVideoEditor --onefile --windowed --add-data="version.txt:." --icon=src/icons/icon.icns src/main.py
        zip -r AutoVideoEditor_macOS.zip dist/AutoVideoEditor
    
    # Linux 构建
    - name: Build application (Linux)
      if: runner.os == 'Linux'
      run: |
        pyinstaller --name AutoVideoEditor --onefile --windowed --add-data="version.txt:." --icon=src/icons/icon.png src/main.py
        zip -r AutoVideoEditor_Linux.zip dist/AutoVideoEditor
    
    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AutoVideoEditor_${{ runner.os }}
        path: |
          AutoVideoEditor_*.zip
        retention-days: 7
        if-no-files-found: error
